### PR TITLE
Batik bugfix

### PR DESCRIPTION
**Pull request by jbobnar**
Found a workaround for the batik my fragment. Because it doesn't have any code to pack, I chose an empty jar from the maven repository. I does not include any code, but is there just to be able to add my fragment manifest.

### CODE REVIEW

**Comment by berryma4** [comment]
again, what's the actual bug, and what's not working from the Eclipse Orbit version.

**Comment by jbobnar** [comment]
The packaging of 1.7 plugins is messed up: org.apache.batik.dom.svg directly requires classes from org.apache.batik.ext.awt, but if you open its manifest you'll see it does not include a dependency to that plugin. That causes a ClassNotFoundException, because plugin can only use classes that are directly on its classpath.

**Comment by berryma4** [comment]
I remember reading that Eclipse had issues bundling 1.7.  Could you add a comment, so when it's fixed, we can go back to Orbit.
Thank you!

**Comment by jbobnar** [comment]
At ITER we are using Orbit's Batik 1.7 release since October already. We had some issues, but in general it's been working OK. Some new features have been added recently and the bug solved by this pull request popped up.

**Pull request merged**
